version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db:27017/blog_db
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db